version: '3.0.0.{build}'

image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
  - ps: dotnet pack -c Release

artifacts:
  - path: bin\Release\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: ofK16Z5FWkIJ5u963EiDdqltNbV3vqERe21htQ0QFEMJicTeEdhfFnTVf7blbRyv
  on:
    APPVEYOR_REPO_TAG: true
