version: '2.1.0.{build}'

image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
  - ps: dotnet pack -c Release

artifacts:
  - path: bin\Release\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: SfN1o6QQanif4GHzA0e1DCBbeBJGwVubM+ckpzSskWNBfDctZWtr6pr4Vdcmr3gB
  on:
    APPVEYOR_REPO_TAG: true
