version: '4.1.0.{build}'

image: Visual Studio 2022

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
  - ps: dotnet pack -c Release

test_script:
  - ps: dotnet new install bin/Release/*.nupkg
  - ps: dotnet new -o ./test flow-plugin --name TestPlugin --keyword ci --pluginAuthor AppVeyor --description "a test plugin from CI"
  - ps: dotnet publish -c Release -r win-x64 --no-self-contained ./test/Flow.Launcher.Plugin.TestPlugin
  - ps: Compress-Archive -Path ./test/Flow.Launcher.Plugin.TestPlugin/bin/Release/win-x64/publish/* -DestinationPath plugin.zip -Force

artifacts:
  - path: bin\Release\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: ofK16Z5FWkIJ5u963EiDdqltNbV3vqERe21htQ0QFEMJicTeEdhfFnTVf7blbRyv
  on:
    APPVEYOR_REPO_TAG: true
