version: '1.0.0.{build}'

image: Visual Studio 2019

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

build_script:
  - ps: dotnet pack -c Release

artifacts:
  - path: bin\Release\*.nupkg
